import {
  type MotionSpec,
  parseMotionSpec,
} from './schema/motion-spec';

const defineSpec = (spec: MotionSpec): MotionSpec => parseMotionSpec(spec);

export const fixtures = {
  KineticTitle: defineSpec({
    version: '1.0',
    name: 'Make ideas move',
    fps: 30,
    width: 1920,
    height: 1080,
    durationInFrames: 180,
    palette: {
      background: '#0b0d12',
      foreground: '#f6f4ef',
      accent: '#ff5c35',
      muted: '#9298a6',
    },
    typography: {
      display: 'space-grotesk',
      body: 'inter',
      tracking: -0.04,
      uppercaseTitles: false,
    },
    accent: {type: 'orbit', intensity: 0.7},
    segments: [
      {
        id: 'opening-title',
        startFrame: 0,
        durationInFrames: 180,
        kind: 'title',
        layout: 'left',
        entrance: 'stagger',
        exit: 'fade',
        lines: [
          {role: 'eyebrow', text: 'LOCAL MOTION SYSTEM', emphasis: false},
          {role: 'title', text: 'Make ideas', emphasis: false},
          {role: 'title', text: 'move.', emphasis: true},
          {role: 'subtitle', text: 'Designed in language. Rendered in code.', emphasis: false},
        ],
      },
    ],
  }),
  QuoteSequence: defineSpec({
    version: '1.0',
    name: 'Momentum quote',
    fps: 30,
    width: 1080,
    height: 1080,
    durationInFrames: 180,
    palette: {
      background: '#f0eadf',
      foreground: '#171713',
      accent: '#2457f5',
      muted: '#6d6a61',
    },
    typography: {
      display: 'fraunces',
      body: 'inter',
      tracking: -0.03,
      uppercaseTitles: false,
    },
    accent: {type: 'grid', intensity: 0.35},
    segments: [
      {
        id: 'quote',
        startFrame: 0,
        durationInFrames: 180,
        kind: 'quote',
        layout: 'center',
        entrance: 'wipe',
        exit: 'shrink',
        lines: [
          {role: 'eyebrow', text: 'A NOTE ON MOMENTUM', emphasis: false},
          {role: 'title', text: 'Start before', emphasis: false},
          {role: 'title', text: 'you feel ready.', emphasis: true},
          {role: 'body', text: 'Clarity follows motion.', emphasis: false},
        ],
      },
    ],
  }),
  ProductLaunch: defineSpec({
    version: '1.0',
    name: 'Nova product launch',
    fps: 30,
    width: 1920,
    height: 1080,
    durationInFrames: 240,
    palette: {
      background: '#090816',
      foreground: '#ffffff',
      accent: '#9f7aea',
      muted: '#aaa4c2',
    },
    typography: {
      display: 'space-grotesk',
      body: 'inter',
      tracking: -0.05,
      uppercaseTitles: false,
    },
    accent: {type: 'glass', intensity: 0.75},
    segments: [
      {
        id: 'product',
        startFrame: 0,
        durationInFrames: 150,
        kind: 'product',
        layout: 'split',
        entrance: 'rise',
        exit: 'fade',
        lines: [
          {role: 'eyebrow', text: 'INTRODUCING NOVA', emphasis: false},
          {role: 'title', text: 'Focus at the', emphasis: false},
          {role: 'title', text: 'speed of thought.', emphasis: true},
        ],
      },
      {
        id: 'product-outro',
        startFrame: 150,
        durationInFrames: 90,
        kind: 'outro',
        layout: 'center',
        entrance: 'scale',
        exit: 'fade',
        lines: [
          {role: 'title', text: 'NOVA', emphasis: true},
          {role: 'subtitle', text: 'Available now', emphasis: false},
        ],
      },
    ],
  }),
  MetricReveal: defineSpec({
    version: '1.0',
    name: 'Growth metric',
    fps: 30,
    width: 1920,
    height: 1080,
    durationInFrames: 180,
    palette: {
      background: '#071a14',
      foreground: '#ebfff6',
      accent: '#61f2ad',
      muted: '#7ca998',
    },
    typography: {
      display: 'jetbrains-mono',
      body: 'inter',
      tracking: -0.05,
      uppercaseTitles: false,
    },
    accent: {type: 'particles', intensity: 0.45},
    segments: [
      {
        id: 'growth',
        startFrame: 0,
        durationInFrames: 180,
        kind: 'metric',
        layout: 'left',
        entrance: 'scale',
        exit: 'fade',
        lines: [
          {role: 'eyebrow', text: 'YEAR OVER YEAR', emphasis: false},
          {role: 'metric', text: '+184%', emphasis: true},
          {role: 'subtitle', text: 'More creators shipping every week', emphasis: false},
        ],
      },
    ],
  }),
  EventPromo: defineSpec({
    version: '1.0',
    name: 'Signal conference',
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 210,
    palette: {
      background: '#15100c',
      foreground: '#fff4e8',
      accent: '#ffb000',
      muted: '#bda992',
    },
    typography: {
      display: 'space-grotesk',
      body: 'inter',
      tracking: -0.04,
      uppercaseTitles: true,
    },
    accent: {type: 'orbit', intensity: 0.5},
    segments: [
      {
        id: 'event',
        startFrame: 0,
        durationInFrames: 210,
        kind: 'event',
        layout: 'center',
        entrance: 'stagger',
        exit: 'shrink',
        lines: [
          {role: 'eyebrow', text: 'BENGALURU · OCT 24', emphasis: false},
          {role: 'title', text: 'SIGNAL', emphasis: true},
          {role: 'title', text: 'DESIGN CONF', emphasis: false},
          {role: 'subtitle', text: 'Ideas worth making visible', emphasis: false},
        ],
      },
    ],
  }),
  LogoOutro: defineSpec({
    version: '1.0',
    name: 'Fanne Khan outro',
    fps: 30,
    width: 1920,
    height: 1080,
    durationInFrames: 120,
    palette: {
      background: '#f5f5f2',
      foreground: '#111111',
      accent: '#ee3f55',
      muted: '#777771',
    },
    typography: {
      display: 'space-grotesk',
      body: 'inter',
      tracking: 0.08,
      uppercaseTitles: true,
    },
    accent: {type: 'none', intensity: 0},
    segments: [
      {
        id: 'brand',
        startFrame: 0,
        durationInFrames: 120,
        kind: 'outro',
        layout: 'center',
        entrance: 'scale',
        exit: 'fade',
        lines: [
          {role: 'title', text: 'FANNE KHAN', emphasis: true},
          {role: 'eyebrow', text: 'MOTION, WITH INTENT', emphasis: false},
        ],
      },
    ],
  }),
} satisfies Record<string, MotionSpec>;

export type FixtureId = keyof typeof fixtures;
